### PR TITLE
fix: add missing checks for stale element reference errors

### LINKED ISSUE #160: Check for stale elements
**What would you like to be added**:
Checking for element staleness (i.e. checking if the element is attached to the current browsing context's page document). A `stale element reference` [webdriver error](https://www.w3.org/TR/webdriver/#dfn-error-code) should be thrown in these cases.

**Why is this needed**:
Required since it's possible webdriver commands can be executed against an element that does not exist in the current document. This could occur when changing browsing contexts as with Switch To Frame.

**Additional context**
`document.body.contains(element)` may be one way to test for this.

### PR DESCRIPTION
**Pull request by poftadeh**
- added `StaleElementReference` error class.
- fixed logic to throw this error in element endpoints whenever an element that is not connected to the DOM is accessed.
- added test for stale element checks

Closes #160.

### CODE REVIEW

File: src/Browser/Browser.ts [hunk 1]
```diff
@@ -336,14 +336,33 @@ class Browser {
...
+   * @throws {NoSuchElement}
+   * @returns {WebElement}
    */
-  getKnownElement(elementId: string): WebElement {
-    let foundElement = null;
-    this.knownElements.forEach(element => {
+  public getKnownElement(elementId: string): WebElement {
+    let foundElement: WebElement = null;
+    this.knownElements.forEach((element: WebElement) => {
       if (element[ELEMENT] === elementId) foundElement = element;
```
Comment (manekenpix) [inline src/Browser/Browser.ts]: What's `ELEMENT`?

Comment (poftadeh) [reply src/Browser/Browser.ts]: Part of the spec, and defined in `constants.js`:

```js
/** [W3C web element identifier constant](https://w3c.github.io/webdriver/#elements) */
export const ELEMENT = 'element-6066-11e4-a52e-4f735466cecf';
```
